<?php
$translate = $this->plugin('translate');
$this->headLink()->appendStylesheet($this->assetUrl('css/resource-page-blocks.css', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;

$itemMedia = $item->media();

$viewers = [];
$miradorViewer = null;
$miradorImageViewer = null;
$universalViewer = null;
$youtubeViewer = null;
$defaultViewer = null;
?>

<?php
// Loop through Item Media and Choose Viewer for the First Item Only
$firstMedia = true;
foreach ($itemMedia as $index => $media) {
    $mediaType = $media->mediaType();
    $mediaRenderer = $media->renderer();
        // Add debugging statements
        // echo "Media Renderer: $mediaRenderer, Media Type: $mediaType<br>";

    if ($firstMedia) {
        if ($mediaRenderer == 'iiifPresentation') {
            $viewers[] = 'mirador';
            $firstMedia = false;
        } elseif ($mediaRenderer == 'iiif') {
            $viewers[] = 'mirador';
            $miradorImageViewer = "<div>" . $this->mirador($item) . "</div>";
            $firstMedia = false;
        } elseif ($mediaRenderer == 'youtube') {
            $viewers[] = 'youtube';
            $youtubeViewer = "<div class='responsive-embed widescreen'>" . $media->render() . "</div>";
            $firstMedia = false;
        } else {
            $viewers[] = 'default';
            $defaultViewer = $media->render();
            $firstMedia = false;
        }
    } else {
        // For additional media, you may want to handle them differently or skip them.
        // You can add additional logic here if needed.
    }
}
?>
<?php $this->trigger('view.show.before'); ?>

<div class="pure-g full-width item-show-section">
    <div class="pure-u-sm-1 pure-u-lg-2-3 pure-u-xl-3-5 item-show-media">
        <div class="l-box">
            <?php 
                // Display the main viewer
                if ($miradorViewer !== null) {
                    echo $miradorViewer;
                }
                elseif ($miradorImageViewer !== null) {
                    echo $miradorImageViewer;
                } 
                elseif ($universalViewer !== null) {
                    echo $universalViewer;
                } 
                elseif ($youtubeViewer !== null) {
                    echo $youtubeViewer;
                } 
                elseif ($defaultViewer !== null) {
                    echo $defaultViewer;
                }
            ?>
        </div>
    </div>
    <div class="pure-u-sm-1 pure-u-lg-1-3 pure-u-xl-2-5">
        <div class="l-box item-show-metadata">
            <div class="item-show-title">
                <?php echo $this->pageTitle($item->displayTitle(null, $valueLang), 2); ?>
            </div>
            <?php echo $this->resourcePageBlocks($item)->getBlocks(); ?>
        </div>
    </div>
</div>
