<div class="<?php echo $this->alignmentClass . ' ' . $this->thumbnailType; ?> file media-embed">
    <div class="attachments">
        <?php foreach($this->attachments as $attachment): ?>
            <div class="item resource">
                <?php
                $item = $attachment->item();
                if ($item):
                ?>
                    <?php
                    $media = $attachment->media() ?: $item->primaryMedia();
                    if ($media):
                        // Removed the link-related code
                        echo $media->render([
                            'thumbnailType' => $thumbnailType,
                        ]);
                    endif;
                    ?>
                    <?php $showTitleOption = $this->showTitleOption; ?>
                    <?php if ($showTitleOption == 'item_title'): ?>
                        <h2><?php echo $item->displayTitle(); ?></h2>
                    <?php elseif ($showTitleOption == 'file_name'): ?>
                        <h2><?php echo $media->displayTitle(); ?></h2>
                    <?php endif; ?>
                <?php endif; ?>

                <?php
                $caption = $attachment->caption();
                if ($caption):
                ?>
                    <div class="caption"><?php echo $caption; ?>
                    </div>
                <?php endif; ?>
                <div class="learn-more">
                    <button class="pure-button-primary button-xlarge"><?php echo $item->link("View full item"); ?></button>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>