<?php
$hyperlink = $this->plugin('hyperlink');
?>
<div class="file media-embed <?php echo $this->escapeHtml(implode(' ', $classes)); ?>">
    <?php foreach($attachments as $attachment): ?>
    <?php $item = $attachment->item(); ?>
    <div class="item resource">
        <?php
        $media = $attachment->media() ?: $item->primaryMedia();
        if ($media):
            if ($mediaDisplay === 'thumbnail') {
                switch ($link) {
                    case 'original':
                        $url = $media->originalUrl();
                        break;
                    case 'item':
                        $url = $item->url();
                        break;
                    case 'media':
                        $url = $media->url();
                        break;
                    default:
                        throw new \InvalidArgumentException(sprintf('Invalid link type "%s"', $linkType));
                }
                echo $hyperlink->raw($this->thumbnail($media, $thumbnailType), $url);
            } else {
                echo $media->render([
                    'thumbnailType' => $thumbnailType,
                    'link' => $link,
                ]);
            }
        endif;
        ?>
        <?php $caption = $attachment->caption(); ?>
        <?php if ($caption): ?>
            <div class="caption"><?php echo $caption; ?></div>
        <?php endif; ?>
        <?php if ($showTitleOption === 'item_title'): ?>
            <h2><?php echo $item->link($item->displayTitle()); ?></h2>
        <?php elseif ($showTitleOption === 'file_name'): ?>
            <h2><?php echo $media->displayTitle(); ?></h2>
        <?php endif; ?>
        <div class="learn-more">
            <button class="pure-button-primary button-xlarge"><?php echo $item->link("View full item"); ?></button>
        </div>
    </div>
    <?php endforeach; ?>
</div>