<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $html
 * @var string $divclass
 * @var string $heading
 */

?>
<?php if (empty($divclass)): ?>

<div class="paragraph-text introduction no-margin-top">
<?php if (!empty($heading)): ?>
<h2><?= $this->escapeHtml($heading) ?></h2>
<?php endif; ?>
<?= $html ?>
</div>

<?php else: ?>

<div class="<?= $this->escapeHtmlAttr($divclass) ?> paragraph-text">
    <?php if (!empty($heading)): ?>
    <h2><?= $this->escapeHtml($heading) ?></h2>
    <?php endif; ?>
    <?= $html ?>
</div>

<?php endif; ?>
