<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var \Omeka\Api\Representation\SiteBlockAttachmentRepresentation[] $attachments
 * @var string $heading
 * @var string $html
 * @var string $alignmentClass "left" or "right"
 * @var string $thumbnailType
 * @var string $showTitleOption "item_title" or "file_name" or "none".
 * @var string $captionPosition "center", "left" or "right".
 */

$escape = $this->plugin('escapeHtml');
$hyperlink = $this->plugin('hyperlink');
$siteSetting = $this->plugin('siteSetting');

$linkType = $siteSetting('attachment_link_type', 'item');

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $filterLocale ? $this->lang() : null;
?>
<div class="media-text-title dark full-width">
    <div class="grid-container">
        <?php if (!empty($heading)): ?>
            <h2 class="block"><?= $escape($heading) ?></h2>
        <?php endif; ?>
        <div class="media-text">
            <div class="<?= $alignmentClass . ' ' . $thumbnailType . ' captions-' . $captionPosition ?> media file">
                <div class="attachments">
                    <?php
                    foreach ($attachments as $attachment):
                        $render = null;
                        $title = null;
                        $item = $attachment->item();
                        if ($item):
                            $media = $attachment->media() ?: $item->primaryMedia();
                            if ($media):
                                $render = $media->render([
                                    'thumbnailType' => $thumbnailType,
                                ]);
                            endif;

                            if ($showTitleOption == 'item_title'):
                                $title = $item->displayTitle(null, $lang);
                            elseif ($media && $showTitleOption == 'file_name'):
                                $title = $media->displayTitle(null, $lang);
                            endif;
                        endif;

                        $caption = $attachment->caption();
                    ?>
                    <div class="item resource">
                        <?= $render ?>
                        <?php if (!empty($caption)): ?>
                        <div class="caption">
                            <?= $caption ?>
                        </div>
                        <?php endif; ?> 
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>
            <div class="text">
                <h2><?php echo $title; ?></h2>
                <?= $html ?>
                <div class="learn-more">
                    <button class="pure-button-primary button-xlarge"><?php echo $item->link("View full item"); ?></button>
                </div>
            </div>
        </div>
    </div>
</div>
