<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var array $locales
 * @var array $locale_labels
 * @var bool $locale_as_code
 */

?>

<?php if ($locales): ?>
    <?php $currentLocale = $this->siteSetting('locale') ?: 'en_US'; ?>
    <div class="language-switcher closed">
        <button id="switcher-toggle" aria-label="Toggle Language Switcher"></button>
        <ul>
            <?php foreach ($locales as $locale): ?>
                <?php $label = ucwords(explode(" (", $locale['locale_label'])[0]); ?>
                <li>
                    <?php if ($currentLocale == $locale['locale']): ?>
                        <a class="active"><span class="radio checked"></span><?= $label ?></a>
                    <?php else: ?>
                        <a href="<?= $locale['url'] ?>"><span class="radio"></span><?= $label ?></a>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>