<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $this->themeSetting('title') ?? $site->title();
$headerColor = $this->themeSetting('header_color');
$headerDark = $this->themeSetting('header_dark') ?? true;
$accentColor = $this->themeSetting('accent_color');
$userBar = $this->userBar();

$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet($this->assetUrl('css/uom-footer.css'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,700;1,300;1,400&display=swap');
$this->headScript()->prependFile($this->assetUrl('js/thedaily.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->jsTranslate();
$this->trigger('view.layout');
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html')->appendAttribute('class', 'theme-multilingual'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>

        <style>
            body {
            <?php if ($accentColor): ?>
                --accent-color: <?= $accentColor; ?>;
            <?php endif; ?>
            <?php if ($headerColor): ?>
                --header-color: <?= $headerColor; ?>;
            <?php endif; ?>
            }
        </style>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>
        <?php echo $userBar; ?>
        <header class="wrapper">
            <h1>
                <a href="<?php echo $site->url(); ?>" class="site-title">
                <?php if ($this->themeSetting('logo')): ?>
                    <img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
                <?php else: ?>
                    <?php echo $escape($siteTitle); ?>
                <?php endif; ?>
                </a>
            </h1>
            <button type="button" class="search-toggle" aria-label="Toggle search" aria-expanded="false"></button>
            <div id="search-container" class="closed">
                <?php echo $this->partial('common/search-form'); ?>
            </div>
            <?php if ($this->getHelperPluginManager()->has('languageSwitcher')) echo $this->languageSwitcher(); ?>
            <button type="button" class="menu-toggle" aria-label="Toggle menu" aria-expanded="false"></button>
        </header>
        
        <nav id="top-nav" class="wrapper closed<?php if (!$headerDark): ?> nav-light<?php endif; ?>">
            <?= $site->publicNav()->menu()->renderMenu(null, [
                'maxDepth' => $this->themeSetting('nav_depth') - 1
            ]); ?>
        </nav>
        
        <div id="content" class="wrapper" role="main">
            <?php echo $this->content; ?>
        </div>
        
        <footer class="footerContainer">							
            <div class="row tripleVertPadding">     
                <div class="eightcol">
                    <div class="footerLogos">
                        <img src="https://www.library.manchester.ac.uk/assets/images/design/national-research-libraries.png" height="63" alt="National Research Libraries">											
                        <p>The University of Manchester Library is one of five National Research Libraries</p>
                    </div>
                </div>     
                <div class="fourcol last">
                    <h2>Connect with us</h2>
                    <ul class="inlineList footer-socialIcons">                
                        <li><a href="https://www.facebook.com/pages/The-University-of-Manchester-Library/25777209922">
                            <img class="lazy" src="https://www.library.manchester.ac.uk/assets/images/design/icon-facebook-large.png" width="40" height="40" data-original="/assets/images/design/icon-facebook-large.png" alt="Facebook page for The University of Manchester Library">
                            <noscript><img class="" src="https://www.library.manchester.ac.uk/assets/images/design/icon-facebook-large.png" width="40" height="40" alt="Facebook page for The University of Manchester Library"></noscript>
                            </a>
                        </li>
                        <li><a href="https://twitter.com/UoMLibrary">
                            <img class="lazy" src="https://www.library.manchester.ac.uk/assets/images/design/icon-twitter-large.png" width="40" height="40" data-original="/assets/images/design/icon-twitter-large.png" alt="Twitter page for The University of Manchester Library">
                            <noscript><img class="" src="https://www.library.manchester.ac.uk/assets/images/design/icon-twitter-large.png" width="40" height="40" alt="Twitter page for The University of Manchester Library"></noscript>
                            </a>
                        </li>
                        <li><a href="https://www.instagram.com/uomlibrary/">
                            <img class="lazy" src="https://www.library.manchester.ac.uk/assets/images/design/icon-instagram.png" width="40" height="40" data-original="/assets/images/design/icon-instagram.png"  alt="Instagram page for The University of Manchester Library">
                            <noscript><img class="" src="https://www.library.manchester.ac.uk/assets/images/design/icon-instagram.png" width="40" height="40" alt="Instagram page for The University of Manchester Library"></noscript>
                            </a>
                        </li>
                        <li><a href="https://www.youtube.com/user/UoMLibrary">
                            <img class="lazy" src="https://www.library.manchester.ac.uk/assets/images/design/icon-youtube-large.png" width="40" height="40" data-original="/assets/images/design/icon-youtube-large.png"  alt="YouTube page for The University of Manchester Library">
                            <noscript><img class="" src="https://www.library.manchester.ac.uk/assets/images/design/icon-youtube-large.png" width="40" height="40" alt="YouTube page for The University of Manchester Library"></noscript>
                            </a>
                        </li>
                        <li><a href="https://www.linkedin.com/showcase/the-university-of-manchester-library">
                            <img class="lazy" src="https://www.library.manchester.ac.uk/assets/images/design/icon-linkedin.png" width="40" height="40" data-original="/assets/images/design/icon-linkedin.png"  alt="LinkedIn page for The University of Manchester Library">
                            <noscript><img class="" src="https://www.library.manchester.ac.uk/assets/images/design/icon-linkedin.png" width="40" height="40" alt="LinkedIn page for The University of Manchester Library"></noscript>
                            </a>
                        </li>													
                    </ul>
                </div>
            </div>
            <hr>       
            <div class="row singleVertPadding">
                <div class="twelvecol">
                    <ul class="inlineList">
                        <li><a href="https://www.manchester.ac.uk/disclaimer/">Disclaimer</a> /</li>
                                    <li><a href="https://www.manchester.ac.uk/discover/privacy-information/data-protection/">Data Protection</a> /</li>
                                    <li><a href="https://www.manchester.ac.uk/copyright/">Copyright notice</a> /</li>
                                    <li><a href="https://www.library.manchester.ac.uk/accessibility/manchester-digital-exhibitions/">Web accessibility</a> /</li>
                                    <li><a href="https://www.manchester.ac.uk/discover/privacy-information/freedom-information/">Freedom of information</a> /</li>
                                    <li><a href="https://www.manchester.ac.uk/discover/governance/charitable-status/">Charitable status</a> /</li>             
                        <li>Royal Charter Number: RC000797</li>
                    </ul>
                </div>
            </div>  
        </footer> 
    </body>
</html>
