<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $this->themeSetting('title') ?? $site->title();
$headerColor = $this->themeSetting('header_color');
$userBar = $this->userBar();

$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
if (!$userBar) { $this->headMeta()->appendName('theme-color', $headerColor ?? "#000"); }
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css2?family=Montserrat:wght@600;800&family=Work+Sans:ital,wght@0,400;0,500;1,400&display=swap');
$this->headScript()->prependFile($this->assetUrl('js/thedaily.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>

        <style>
            <?php if ($accentColor = $this->themeSetting('accent_color')): ?>
            .advanced-search,
            #featured .record a,
            .site-page-pagination a,
            #featured .record a,
            .site-page-pagination a,
            .results .result-title a {
                color: <?php echo $accentColor; ?>
            }

            p a,
            span a,
            .button,
            button,
            input[type="submit"],
            header nav > ul,
            .secondary-nav li a,
            .pagination a.button,
            .item-pagination a,
            #featured .featured-meta h3,
            .value a span,
            .sub-menu,
            .results li a,
            .results > ul + a {
                background-color: <?php echo $accentColor; ?>;
            }
            
            .radio::before,
            .radio::after {
                border-color: <?php echo $accentColor; ?>;
            }
            <?php endif; ?>
            <?php if ($headerColor): ?>
            header {
                background-color: <?php echo $headerColor; ?>;
            }
            <?php endif; ?>

            <?php if ($this->themeSetting('header_dark') == true): ?>
            header a,
            ul.language-switcher,
            .search-toggle,
            header nav .menu-toggle {
                color: #000;
            }
            
            #switcher-toggle {
                filter: unset;
            }
            <?php endif; ?>
        </style>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>
        <?php echo $userBar; ?>
        <header>
            <div class="wrapper">
                <h1>
                    <a href="<?php echo $site->url(); ?>" class="site-title">
                    <?php if ($this->themeSetting('logo')): ?>
                        <img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
                    <?php else: ?>
                        <?php echo $escape($siteTitle); ?>
                    <?php endif; ?>
                    </a>
                </h1>
                <button type="button" class="search-toggle" aria-label="Toggle search" aria-expanded="false"></button>
                <div id="search-container" class="closed">
                    <?php echo $this->partial('common/search-form'); ?>
                </div>
                <?php if ($this->getHelperPluginManager()->has('languageSwitcher')) echo $this->languageSwitcher(); ?>
                <nav id="top-nav" class="closed">
                <button type="button" class="menu-toggle" aria-label="Toggle menu" aria-expanded="false"></button>
                <?php
                echo $site->publicNav()->menu()->renderMenu(null, [
                    'maxDepth' => $this->themeSetting('nav_depth') - 1
                ]);
                ?>
                </nav>
            </div>
        </header>
        <div id="content" class="wrapper" role="main">
            <?php echo $this->content; ?>
        </div>
        <footer class="wrapper">
            <?php if ($footerContent = $this->themeSetting('footer')): ?>
            <?php echo $footerContent; ?>
            <?php else: ?>
                <?php echo $this->translate('Powered by Omeka S'); ?>
            <?php endif; ?>
        </footer>
    </body>
</html>
